name: qbittorrent-nox-sterlingh # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: qbittorrent-nox
summary: a command line Bittorrent client written in C++ / Qt
description: |
  **qBittorrent-nox** is  an  advanced command-line Bittorrent client written in C++ / Qt using the libtorrent-rasterbar library by Arvid Norberg.  qBittorrent-nox  aims  to  be  a  good alternative  to  other  command  line  bittorrent clients and provides features similar to popular graphical clients.

  qBittorrent-nox is fast, stable, light and it supports unicode.  It also comes  with  UPnP port forwarding / NAT-PMP, encryption (Vuze compatible), FAST extension (mainline) and PeX support (utorrent compatible).
  
  qBittorrent-nox is meant to be controlled via its feature-rich Web UI which is  accessible as  a  default  on  [http://localhost]|(http://localhost:8080).   The  Web UI access is secured and the default account user name is “admin” with “adminadmin” as a password.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures: [amd64, arm64]

parts:
  qbittorrent-nox:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/qbittorrent/qBittorrent.git
    source-branch: v4_6_x
    environment:
      
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_EXE_LINKER_FLAGS_RELEASE=-s
      - -DCMAKE_INSTALL_PREFIX=''
      - -DGUI=OFF
      - -DQT6=ON
    override-pull: |
      craftctl default
      craftctl set "version=$(git describe | sed 's/^release-//')"
    build-packages:
      - zlib1g-dev
      - libssl-dev
      - qt6-base-dev
      - qt6-tools-dev
      - libqt6svg6-dev
      - linguist-qt6
      - qt6-l10n-tools
      - qt6-tools-dev-tools
    stage-packages:
      - python3
      - libqt6core6
      - libqt6network6
      - libqt6sql6
      - libqt6xml6
      - libb2-1
      - libdouble-conversion3
      - libgomp1
      - libicu70
      - libpcre2-16-0
      - libproxy1v5
    prime:
      - usr/lib/*/libQt6Core.*
      - usr/lib/*/libQt6Network.*
      - usr/lib/*/libQt6Sql.*
      - usr/lib/*/libQt6Xml.*
      - usr/lib/*/libb2.*
      - usr/lib/*/libdouble-conversion.*
      - usr/lib/*/libgomp.*
      - usr/lib/*/libicudata.*
      - usr/lib/*/libicui18n.*
      - usr/lib/*/libicuuc.*
      - usr/lib/*/libpcre2.*
      - usr/lib/*/libpcre2-*
      - usr/lib/*/libproxy.*
      - bin
    after:
      - libtorrent

  libtorrent:
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-dev
      - libssl-dev
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=''
      - -DBUILD_SHARED_LIBS=OFF
    source: https://github.com/arvidn/libtorrent.git
    source-branch: RC_1_2
    prime:
      - -*

apps:
  qbittorrent-nox:
    command: bin/qbittorrent-nox
    daemon: simple
    stop-mode: sigint-all
    environment:
      ISTHISON: 1
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
